# Домашнее задание №9 «Библиотека numpy. Вычислительные задачи»

# Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [8]:
import numpy as np
a = np.arange(0, 10)
print(a[::-1])
#a = np.arange(10, 0, -1)
#print(a)

[9 8 7 6 5 4 3 2 1 0]


# Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [11]:
import numpy as np
a = np.diag(np.arange(20, 10, -2))
print(a)
print(sum(a[np.nonzero(a)]))


[[20  0  0  0  0]
 [ 0 18  0  0  0]
 [ 0  0 16  0  0]
 [ 0  0  0 14  0]
 [ 0  0  0  0 12]]
80


# Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [14]:
a = np.array([[4, 2, 1],[1, 3, 0],[5, 4, 0]])
b = np.array([4, 12, -3])
import numpy as np
from numpy import linalg
linalg.solve(a,b)

array([-5.18181818,  5.72727273, 13.27272727])

# Задача 4 
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [ ]:
from IPython.display import Image
Image("user_matrix.JPG")

Матрица в виде numpy array

In [ ]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [ ]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])


Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [18]:
import matplotlib.pyplot as plt
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

for i in users_stats:
    c = cosine(i, next_user_stats)
    print(c)

NameError: name 'cosine' is not defined